routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Route::get('/general_manager', 'HomeController@homeGm')->name('home_manager');

Route::get('/case_other', 'HomeController@homeGm_other')->name('case_other');

Route::get('/home', 'HomeController@index')->name('home')->name('search_kaw');

Route::get('/landing', 'HomeController@landing')->name('landing');

Route::get('/list', 'HomeController@listing')->name('list');

Route::get('/detail', 'HomeController@detail')->name('detail');

Route::get('/callkawasan', 'HomeController@callkawasan')->name('callkawasan');

Route::resource('/karyawan', 'KaryawanController');

Route::get('/searchajax',array('as'=>'searchajax','uses'=>'AutoCompleteController@autoComplete'));

Route::get('/search' , 'HomeController@search');

Route::get('/testing' , 'HomeController@testing');

Route::get('/case_edit', 'HomeController@case_edit')->name('case_edit');

Route::post('/case_list/update', 'HomeController@case_edit_p');

Route::get('/case_list/indexs', 'HomeController@lists_index')->name('list_indexs');

Route::get('/reset_pass', 'ResetpassController@resetpass');

Auth::routes();

Route::prefix('backend')->group(function(){

	Route::get('/admin/logaktivitas' , 'ListaktivitasController@index');
	Route::post('/admin/logaktivitas/showdata' , 'ListaktivitasController@showdata');
	Route::post('/admin/logaktivitas/changeProyek', 'ListaktivitasController@changeProyek')->name('admin.changeproyek');
	Route::get('/admin/logaktivitas/showdetail', 'ListaktivitasController@showDetail')->name('admin.showdetail');

	Route::resource('/admin/posting', 'PostingController');

	Route::resource('/admin/kategori', 'KategoriController');
	Route::resource('/admin/divisi', 'DivisiController');

	// New case Ciputra
	Route::resource('/admin/cases', 'CasesController');

	Route::get('/admin/manager/list','CasesController@lists_data')->name('cases.lists_data');
	Route::get('/admin/manager/case_edit', 'CasesController@case_edit_manager')->name('case_edit_manager');

	Route::get('/admin/manager/list2','CasesController@lists_data2')->name('cases.lists_data2');

	// Route::get('/admin/custom/nocase', 'CustomController@nocase')->name('customs.nocases');

	// Route::patch('/admin/cases/{id}',[
	//     'as' => 'admin.cases.edits',
	//     'uses' => 'CasesController@update'
	// ]);

	Route::get('/admin/arsip/list','CasesController@arsips')->name('cases.arsip');
	
	Route::resource('/admin/proyek', 'ProyekController');

	Route::resource('/admin/member', 'MemberController');

	Route::resource('/admin/subjectc', 'SubjectcController');
	Route::post('/admin/subjectc/search' , 'SubjectcController@searching')->name('admin.searchsubject');

	Route::resource('/admin/blok', 'BlokController');
	Route::post('/admin/blok/search' , 'BlokController@searching')->name('admin.bloksubject');

	Route::resource('/admin/kawasan', 'KawasanController');
	Route::get('/admin/kawasan' , 'KawasanController@index')->name('admin.searchkawasan');

	Route::resource('/admin/tipes', 'TipesController');
	Route::get('/admin/tipes' , 'TipesController@index')->name('admin.tipesindexs');

	Route::resource('/admin/setuplog', 'SetuplogController');
	Route::resource('/admin/grouping', 'GroupingController');

	Route::get('/admin/admins' , 'AdminController@index2');
	Route::post('/admin/admins/postInsert' , 'AdminController@postInsert');
	Route::get('/admin/admins/edit/{id}' , 'AdminController@edit');
	Route::post('/admin/admins/update/{id}' , 'AdminController@update');
	Route::get('/admin/admins/delete/{id}' , 'AdminController@delete');

	Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
	Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');

	Route::get('/','AdminController@index')->name('admin.dashboard');

	Route::post('ajaximage', function(){
		$file = Request::file('file');
		$destinationPath = public_path().'/uploads/';
		$filename = $file->getClientOriginalName();
		$file->move($destinationPath, $filename);
		echo url().'/uploads/'. $filename;
	});

	Route::get('/admin/category/index',['uses'=>'CategoryController@index'])->name('category.index');
	Route::get('/admin/category/edit',['uses'=>'CategoryController@edit'])->name('category.edit');
	Route::get('/admin/category/delete',['uses'=>'CategoryController@delete'])->name('category.delete');
	
	Route::get('/admin/category-tree-view',['uses'=>'CategoryController@manageCategory']);
	Route::get('/admin/category-tree-view2',['uses'=>'CategoryController@treeView']);

	Route::post('/admin/edit-category',['as'=>'edit.category','uses'=>'CategoryController@editData']);

	Route::post('/admin/add-category',['as'=>'add.category','uses'=>'CategoryController@addCategory']);

	Route::get('/admin/custom/nocase', 'CustomController@nocase')->name('customs.nocases');
	Route::get('/admin/custom/showkawasan', 'CustomController@showkawasan')->name('customs.showkawasan');
	Route::get('/admin/custom/showtipe', 'CustomController@showtipe')->name('customs.showtipe');

	Route::get('/admin/report/index', 'ReportController@index');
	Route::get('/admin/report/excel', 'ReportController@excel');
});

Route::get('/logout-admin' , 'Auth\AdminLoginController@logout')->name('admin.logout');

Route::get('/sop_view' , 'ViewSOPController@index')->name('sop_view');

resources/views/case/arsip.blade.php
@extends('layouts.master')
@section('content-header')
<section class="content-header inside">
      <h1>
        Data Case
        <small>Control panel</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Data Case</li>
      </ol>
    </section>
@endsection
@section('data-content')
 <div class="row">
     <div class="col-xs-12">
        @if (session('notifikasi'))
            <div class="alert alert-success">
              <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                {{ session('notifikasi') }}
            </div>
        @endif
        <div class="box">
         <div class="box-header">
            <h3>Data Case</h3>
         </div>
         <div class="box-body">

             @if(count($cases) > 0)
                <table class="table lists_case_m">
                    <thead>
                        <tr>
                            <th>Proyek</th>
                            <th>PIC</th>
                            {{-- <th>Item Pekerjaan</th> --}}
                            <th>No Case</th>
                            <th>Status</th>
                            <th>#</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($cases as $data)
                        <tr class="{{ $data->status_data }}">
                            <td>{{ $data->nama_proyek }}</td>
                            <td>{{ $data->nama_divisi }}</td>
                            {{-- <td>{{ ucfirst(trans($data->nama_item)) }}</td> --}}
                            <td>{{ $data->no_case }}</td>
                            <td>{{ ($data->status == '1')? "OPEN": "CLOSE" }}</td>
                            <td>-</td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            @else
            arsip kosong
            @endif
            <?php echo $cases->render(); ?>
            <div class="clear clearfix" style="height: 45px;"></div>
         </div>
         </div>
     </div>
 </div>
<hr>
 
@endsection

resources/views/case/index.blade.php
@extends('layouts.master')
@section('content-header')
<section class="content-header inside">
      <h1>
        Data Case
        <small>Control panel</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Data Case</li>
      </ol>
    </section>
@endsection
@section('data-content')
 <div class="row">
     <div class="col-xs-12">
        @if (session('notifikasi'))
            <div class="alert alert-success">
              <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                {{ session('notifikasi') }}
            </div>
        @endif
        <div class="box">
         <div class="box-header">
            <div class="row">
              <div class="col-md-4">
                <h3>Data Case <span class="customs_search">@if ( $filters_divisi ) <small>Kontraktor: {{ $filters_divisi->email }}</small>  @endif</span>
                </h3>
                <a href="{{ URL::route('cases.create') }}" class="btn btn-primary">Tambah Case</a>
              </div>
              <div class="col-md-8">
                <div class="text-right" style="margin-top: 20px;">
                  <form action="{{action('CasesController@index')}}" method="get" role="search">
                    {{-- {{ csrf_field() }} --}}
                      <div class="d-block align-middle">
                          <div class="d-inline-block align-middle pr-2">
                            <label for="">Pilih SUPERVISOR</label>
                          </div>
                          <div class="d-inline-block align-middle pr-2">
                            <select name="spv_id" class="form-control" id="filters_proyekfrm">
                              <option value="">All Supervisor</option>
                              @foreach ($admins as $key => $value)
                                @if ($filter_proyek)
                                  <option @if ($value->id_admin == $filter_proyek->id_admin) selected="selected" @endif  value="{{ $value->id_admin }}">{{ucfirst(trans($value->nama))}}</option>
                                @else
                                  <option value="{{ $value->id_admin }}">{{ucfirst(trans($value->nama))}}</option>
                                @endif
                              @endforeach
                            </select>
                          </div>
                          <div class="d-inline-block align-middle pr-2">
                            <input type="text" class="form-control" name="q" placeholder="Search data" @if($q)value="{{ $q }}"@endif> <span class="input-group-btn">
                            </span>
                          </div>
                          <div class="d-inline-block align-middle">
                            <button type="submit" class="btn btn-default">
                                <span class="glyphicon glyphicon-search"></span>
                            </button>
                          </div>
                      </div>
                  </form>
                  <div class="clear"></div>
                </div>
              </div>
            </div>
         </div>
         <div class="box-body">

             @if(count($cases) > 0)
                <table class="table lists_case_m">
                    <thead>
                        <tr>
                            <th>Foto Hasil Perbaikan</th>
                            <th>KONTRAKTOR</th>
                            <th>BLOK / KAVLING</th>
                            <th>Status</th>
                            <th>#</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($cases as $data)
                        <tr class="{{ $data->status_data }}">
                            <td><img src="{{ URL::to('/upload/case/'.$data->foto_sesudah )}}" alt="" class="img-thumbnail img-fluid" style="max-width: 55px;"></td>
                            <td>{{ $data->nama_divisi }}</td>
                            <td>{{ $data->blok_kavling }}</td>
                            <td>{{ ($data->status == '2')? "CLOSE": "OPEN" }}</td>
                            <td>
                                <a href="{{action('CasesController@show', $data->id)}}" class="btn btn-info"></i> Edit</a>
                                <form action="{{action('CasesController@destroy', $data->id)}}" method="post" class="hapus" style="display:inline">
                                {{csrf_field()}}
                                <input name="_method" type="hidden" value="DELETE">
                                <button class="btn btn-danger to_delete" type="submit">Delete</button>
                                </form>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            @else
            belum ada data
            @endif
            <?php echo $cases->render(); ?>

            <div class="alert small" role="alert" style="background: #f2f2f2; margin-top: 15px;">
              *) Note:<br>
              Data done progress 100% - warna hijau. <br>
              Case tercancel/ belum selesai - warna merah<br>
              Data case 1-2hari akan selesai - warna orange<br>
              Data case ter progress - warna abu-abu
              <div class="clear"></div>
            </div>

         </div>
         </div>
     </div>
 </div>
<hr>

<script type="text/javascript">
  $(function(){

    $("button.to_delete").click(function() {

        var isGood=confirm('Are You Sure?');
        if (isGood) {
          return true
        } else {
          return false;
        }

    });

  });
</script>
@endsection

resources/views/case/indexes_2.blade.php
@extends('layouts.master')
@section('content-header')
<section class="content-header inside">
      <h1>
        Data Listing Case
        <small>Control panel</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Data Listing Case</li>
      </ol>
    </section>
@endsection
@section('data-content')

<div class="row justify-content-center">
        <div class="col-md-11">

            <a href="#" onclick="window.history.back();" class="btn btn-link"><i class="fa fa-chevron-left"></i> Kembali</a>
            <div class="card">
                <div class="card-header">
                <div class="row">
                    <div class="col-md-6">
                      Dashboard  
                    </div>
                    <div class="col-md-6 text-right">
                        <small>PIC: <b>{{ $divisi }}</b></small>
                    </div>
                </div>
                </div>
                <div class="card-body p-5">
                    <div class="lists-shortcut">
                        <div class="table-responsive">
                            @if(count($model) > 0)
                               <table class="table lists_case_m">
                                <thead>
                                    <tr>
                                        <th>No.</th>
                                        <th>Foto Sebelumnya</th>
                                        <th>BLOK / KAVLING</th>
                                        <th>Instruksi</th>
                                        <th>Foto Hasil Perbaikan</th>
                                        <th>Status</th>
                                        <th>-</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($model as $key => $data)
                                    <tr class="{{ $data->status_data }}">
                                      <td>{{ $data->no_case }}</td>
                                      <td>
                                        <div class="well-pic" style="max-width: 80px;"><img class="img-responsive" src="{{ URL::to('/upload/case/'. $data->foto_sebelum )}}" alt=""></div>
                                      </td>
                                      <td>{{ $data->blok_kavling }}</td>
                                      <td>{{ $data->content }}</td>
                                      <td>
                                        <div class="well-pic" style="max-width: 80px;"><img class="img-responsive" src="{{ URL::to('/upload/case/'. $data->foto_sesudah )}}" alt=""></div>
                                      </td>
                                      <td>{{ ($data->status == 1)? "OPEN": "CLOSE" }}</td>
                                      <td><a href="{{ URL::route('case_edit_manager', ['id' => $data->id]) }}" class="btn btn-link"><i class="fa fa-eye"></i></a></td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                            @else
                            belum ada data
                            @endif
                            <?php echo $model->render(); ?>
                           <div class="clear clearfix"></div>
                        </div>
                    </div>
                    <div class="clear clearfix"></div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/case/indexes_3.blade.php
@extends('layouts.master')
@section('content-header')
<section class="content-header inside">
      <h1>
        Data Listing Case
        <small>Control panel</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Data Listing Case</li>
      </ol>
    </section>
@endsection
@section('data-content')

<div class="row justify-content-center">
        <div class="col-md-11">

            <a href="#" onclick="window.history.back();" class="btn btn-link"><i class="fa fa-chevron-left"></i> Kembali</a>
            <div class="card">
                <div class="card-header">
                <div class="row">
                    <div class="col-md-6">
                      Dashboard  
                    </div>
                    <div class="col-md-6 text-right">
                        <small>SUPERVISOR: <b>{{ $divisi }}</b></small>
                    </div>
                </div>
                </div>
                <div class="card-body p-5">
                    <div class="lists-shortcut">
                        <div class="table-responsive">
                            @if(count($model) > 0)
                               <table class="table lists_case_m">
                                <thead>
                                    <tr>
                                        <th>No.</th>
                                        <th>Foto Sebelumnya</th>
                                        <th>BLOK / KAVLING</th>
                                        <th>Instruksi</th>
                                        <th>Foto Hasil Perbaikan</th>
                                        <th>Status</th>
                                        <th>-</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($model as $key => $data)
                                    <tr class="{{ $data->status_data }}">
                                      <td>{{ $data->no_case }}</td>
                                      <td>
                                        <div class="well-pic" style="max-width: 80px;"><img class="img-responsive" src="{{ URL::to('/upload/case/'. $data->foto_sebelum )}}" alt=""></div>
                                      </td>
                                      <td>{{ $data->blok_kavling }}</td>
                                      <td>{{ $data->content }}</td>
                                      <td>
                                        <div class="well-pic" style="max-width: 80px;"><img class="img-responsive" src="{{ URL::to('/upload/case/'. $data->foto_sesudah )}}" alt=""></div>
                                      </td>
                                      <td>{{ ($data->status == 1)? "OPEN": "CLOSE" }}</td>
                                      <td><a href="{{ URL::route('case_edit_manager', ['id' => $data->id]) }}" class="btn btn-link"><i class="fa fa-eye"></i></a></td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                            @else
                            belum ada data
                            @endif
                            <?php echo $model->render(); ?>
                           <div class="clear clearfix"></div>
                        </div>
                    </div>
                    <div class="clear clearfix"></div>
                </div>
            </div>
        </div>
    </div>

@endsection